---
kind: pipeline
name: default

clone:
  disable: true

steps:
  - name: clone
    image: docker.io/bdebyl/alpine-git
    commands:
      - git clone https://github.com/bdebyl/docker-partkeepr.git .
      - git checkout $DRONE_COMMIT

  - name: gate-master
    image: docker.io/bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only HEAD~1..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        - master

  - name: gate-pr
    image: docker.io/bdebyl/alpine-git
    commands:
      - git fetch origin +refs/heads/master
      - git show-ref
      - git diff --name-only $(git merge-base refs/remotes/origin/master HEAD)..HEAD | grep Dockerfile || exit 78
    when:
      branch:
        exclude:
          - master

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: bdebyl/partkeepr
    when:
      branch:
        - master
---
kind: signature
hmac: e35fd18a91a41d7610dfec8a2dced25883bc8f33c193fa311e7025393993414a

...
